version: '3.8'

services:
  # ===== SERVICIO PRINCIPAL =====
  milos-shop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=file:/app/data/milos_shop.db
      - SESSION_SECRET=${SESSION_SECRET:-milos-shop-docker-secret}
      - ADMIN_WS_TOKEN=${ADMIN_WS_TOKEN:-admin-docker-token}
    volumes:
      - milos-shop-data:/app/data
      - ./attached_assets:/app/attached_assets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/services', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - milos-shop-network

  # ===== BASE DE DATOS POSTGRESQL (OPCIONAL) =====
  # Descomenta estas líneas si quieres usar PostgreSQL en lugar de SQLite
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=milos_shop
  #     - POSTGRES_USER=milos_user
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-milos_password}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   networks:
  #     - milos-shop-network

  # ===== SERVICIO DE DESARROLLO =====
  # Para desarrollo local con hot-reload
  milos-shop-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - DATABASE_URL=file:/app/milos_shop.db
      - SESSION_SECRET=${SESSION_SECRET:-milos-shop-dev-secret}
      - ADMIN_WS_TOKEN=${ADMIN_WS_TOKEN:-admin-dev-token}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - milos-shop-network

volumes:
  milos-shop-data:
    driver: local
  # postgres-data:
  #   driver: local

networks:
  milos-shop-network:
    driver: bridge