version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"   # API HTTP
      - "6334:6334"   # API gRPC
    volumes:
      - qdrant_storage:/qdrant/storage

  miloshop-backend:
    build: ./backend
    container_name: miloshop-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm run dev  # o el comando que uses en Express

  miloshop-frontend:
    build: ./frontend
    container_name: miloshop-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    depends_on:
      - miloshop-backend
    ports:
      - "5173:5173" # Vite frontend
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  qdrant_storage:
